apiVersion: v1
kind: Service
metadata:
  name: cloud-lb
spec:
  type: LoadBalancer     # If cluster is on a cloud platform, this will provision one of the cloud platform's load balancers to send traffic to this Service
  ports:
  - port: 9000           # The port that this Service will be listening on
    targetPort: 8080     # Forwards traffic to port 8080 on the Pods that match the selector
  selector:
    chapter: services
